# Generated by Django 5.1.2 on 2024-12-10 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pointage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('matricule', models.CharField(max_length=100)),
                ('agent', models.CharField(max_length=100)),
                ('arrivee', models.CharField(max_length=100)),
                ('depart', models.CharField(max_length=100)),
            ],
        ),
    ]
