# Generated by Django 5.1.2 on 2024-12-10 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointage',
            name='locdepart',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pointage',
            name='depart',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
