# Generated by Django 5.1.2 on 2024-12-10 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_pointage_locdepart_alter_pointage_depart'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointage',
            name='locarrivee',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
