# Generated by Django 5.1.2 on 2025-01-14 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_pointage_locarrivee'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointage',
            name='debutpause',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pointage',
            name='finpause',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pointage',
            name='pcarrivee',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pointage',
            name='pcdebutpause',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pointage',
            name='pcdepart',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pointage',
            name='pcfinpause',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pointage',
            name='locarrivee',
            field=models.CharField(max_length=100),
        ),
    ]
