# Generated by Django 5.1.2 on 2025-01-15 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_pointage_debutpause_pointage_finpause_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pointage',
            old_name='pcdebutpause',
            new_name='locdebutpause',
        ),
        migrations.RenameField(
            model_name='pointage',
            old_name='pcdepart',
            new_name='locfinpause',
        ),
        migrations.RemoveField(
            model_name='pointage',
            name='pcarrivee',
        ),
        migrations.RemoveField(
            model_name='pointage',
            name='pcfinpause',
        ),
    ]
